### ISSUE TITLE
[feature request] write changelog

### ISSUE THREAD

**Issue by aleung** [ungoldman/changelog-parser#45]
Is there any plan to implement the feature to write back into the changelog markdown file?

This feature is useful to programmatically update the changelog, for example in auto release job.

**Comment by ungoldman** [comment]
Hi @aleung 👋 

This module is pretty exclusively a parser, so writing back to the parsed changelog it out of scope for the project. However it would be very possible to use this module in another project meant to write to changelogs programmatically. Perhaps you could take on this project!

Good luck ✌️
